services:
  frontend:
    build:
      context: ./frontend
      args:
        NEXT_PUBLIC_BACKEND_URL: http://backend:8080
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_BACKEND_URL=http://backend:8080
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      - PYTHON_SERVICE_URL=http://python-ml:8000
    depends_on:
      - python-ml

  python-ml:
    build: ./python-ml
    ports:
      - "8000:8000"
